# Generated by Django 4.0.3 on 2022-03-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntroOfDrakeParker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
